version: '3'
 
services:
  postgres:
    image: postgres:10.7
    restart: always
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=desafio_globo
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'
    expose:
      - 5438
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
          # copy the sql script to create tables
      # - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
          # copy the sql script to fill tables
      # - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
 
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    labels:
      name: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./conf-rabbit/rabbitmq.conf:/etc/rabbitmq/rabbitmq.config